const DEFAULT_ARTICLES = [
  // ==================== ARTICLE ====================
  {id:'a1',title:'Belajar Coding dari Nol untuk Pemula',type:'article',author:'Ysdev',date:'20 Sep 2026',read:12,
   excerpt:'Panduan lengkap memulai perjalanan coding tanpa latar belakang IT.',
   content:'<h2>Kenapa Harus Belajar Coding?</h2><p>Coding bukan cuma buat programmer. Di era digital, coding adalah <b>kemampuan literasi baru</b> — seperti membaca dan menulis. Dengan coding, kamu bisa bikin website, aplikasi, game, atau otomatisasi pekerjaan.</p><p>Menurut data industri, permintaan developer di Indonesia naik 35% setiap tahun. Gaji rata-rata programmer pemula Rp 6-10 juta/bulan. Yang sudah senior bisa 30-50 juta.</p><h2>1. Pilih Bahasa Pertama</h2><p>Jangan bingung. Untuk pemula, rekomendasi:<br><b>Python</b> — sintaks sederhana, cocok untuk logika dasar.<br><b>JavaScript</b> — langsung jalan di browser, hasilnya kelihatan.<br><b>Kotlin</b> — kalau mau bikin aplikasi Android.</p><p>Jangan pilih bahasa cuma karena "populer". Pilih yang sesuai tujuanmu. Mau bikin web? JavaScript. Mau analisis data? Python. Mau app Android? Kotlin.</p><h2>2. Kuasai Dasar Logika</h2><p>Semua bahasa punya konsep yang sama: variabel, kondisi (if-else), perulangan (for/while), fungsi, dan struktur data (array, object). Kuasai ini dulu sebelum lompat ke framework.</p><p>Contoh:</p><pre><code>// Variabel\nlet nama = "Yadi";\nlet umur = 20;\n\n// Kondisi\nif (umur >= 18) {\n    console.log("Dewasa");\n} else {\n    console.log("Anak-anak");\n}\n\n// Perulangan\nfor (let i = 0; i &lt; 5; i++) {\n    console.log(i);\n}</code></pre><h2>3. Latihan Setiap Hari</h2><p>15 menit sehari lebih baik dari 5 jam sekali seminggu. Konsistensi > intensitas. Otak belajar coding lewat repetisi.</p><h2>4. Bangun Proyek Kecil</h2><p>Kalkulator, to-do list, atau game tebak angka. Proyek nyata bikin kamu cepat paham. Mulai dari yang sederhana, naik bertahap.</p><h2>5. Jangan Takut Error</h2><p>Error adalah guru terbaik. Setiap bug yang kamu selesaikan = skill naik 1 level. Bahkan programmer 20 tahun pengalaman masih error tiap hari.</p><h2>6. Gabung Komunitas</h2><p>Belajar sendiri bisa, tapi lebih cepat kalau punya teman. Gabung forum, grup chat, atau komunitas lokal. Diskusi = belajar 2x lebih cepat.</p><h2>Kesimpulan</h2><p>Belajar coding itu maraton, bukan sprint. Fokus, sabar, dan terus latihan. Setelah 3 bulan konsisten, kamu bakal heran sama kemampuanmu sendiri. Selamat berpetualang!</p>'},

  {id:'a2',title:'10 Kesalahan Programmer Pemula yang Harus Dihindari',type:'article',author:'Ysdev',date:'18 Sep 2026',read:10,
   excerpt:'Hindari 10 jebakan umum ini biar perjalanan codingmu lancar.',
   content:'<h2>Pendahuluan</h2><p>Setiap programmer pernah jadi pemula. Tapi ada kesalahan yang kalau dihindari, bisa menghemat waktu berbulan-bulan.</p><h2>1. Langsung Lompat ke Framework</h2><p>Belum paham dasar JavaScript, langsung React. Belum paham Java, langsung Spring Boot. Ini resep gagal. Framework itu cuma alat — kalau fundamentalnya nggak kuat, kamu cuma bisa copy-paste tanpa paham.</p><h2>2. Copy-Paste Tanpa Paham</h2><p>Stack Overflow itu teman, bukan pengganti otak. Pahami dulu, baru pakai. Kalau cuma copy-paste, kamu nggak akan bisa debug pas error.</p><h2>3. Tidak Pakai Version Control</h2><p>Git itu wajib. Bayangkan kerja 3 hari, laptop rusak, kode ilang semua. Version control menyelamatkan hidupmu.</p><h2>4. Skip Dokumentasi</h2><p>Dokumentasi resmi adalah sumber paling akurat. Biasanya lebih update dari tutorial. Kebiasaan baca docs = skill jangka panjang.</p><h2>5. Takut Bertanya</h2><p>Nggak ada pertanyaan bodoh. Yang bodoh itu diam dan stuck berhari-hari. Tanya di forum, grup, atau komunitas.</p><h2>6. Tidak Bikin Catatan</h2><p>Catat error & solusinya. Nanti bisa jadi cheat sheet pribadi. Setelah 1 tahun, catatanmu lebih berharga dari tutorial manapun.</p><h2>7. Belajar Terlalu Banyak Bahasa</h2><p>Kuasai 1 dulu sampai mahir, baru eksplorasi. "Jack of all trades, master of none" itu nyata.</p><h2>8. Tidak Pernah Selesai Proyek</h2><p>Mulai 10 proyek, selesai 0. Lebih baik 1 proyek jadi, walau sederhana. Portfolio > teori.</p><h2>9. Mengabaikan Kesehatan</h2><p>Duduk 12 jam, mata rusak, punggung sakit. Istirahat itu produktif. Pakai teknik Pomodoro: 25 menit kerja, 5 menit istirahat.</p><h2>10. Berhenti di Tengah Jalan</h2><p>Belajar coding 3 bulan lalu berhenti? Sayang. Terus lanjut. Konsistensi mengalahkan bakat.</p><h2>Penutup</h2><p>Semua programmer hebat pernah melewati fase pemula. Yang membedakan: mereka tidak berhenti. Semangat!</p>'},

  {id:'a3',title:'Roadmap Full-Stack Developer 2026 (Lengkap)',type:'article',author:'Ysdev',date:'15 Sep 2026',read:15,
   excerpt:'Urutan belajar dari HTML sampai deploy — lengkap dan terstruktur.',
   content:'<h2>Pendahuluan</h2><p>Full-stack developer = orang yang bisa handle frontend + backend + deploy. Ini roadmap lengkap 12-18 bulan.</p><h2>FASE 1: Frontend (3-6 bulan)</h2><p><b>1. HTML & CSS</b> — struktur & tampilan. Kuasai semantic HTML, flexbox, grid, responsive design.</p><p><b>2. JavaScript ES6+</b> — variabel let/const, arrow function, destructuring, promise, async/await, modules.</p><p><b>3. DOM Manipulation</b> — querySelector, event listener, classList, fetch API.</p><p><b>4. Framework</b> — pilih React (paling banyak dicari), Vue (paling gampang), atau Svelte (paling ringan).</p><p><b>5. State Management</b> — Redux, Zustand, atau Pinia. Cukup kuasai satu.</p><p><b>6. Build Tools</b> — Vite, Webpack, atau esbuild.</p><h2>FASE 2: Backend (6-9 bulan)</h2><p><b>1. Bahasa server</b> — Node.js, Python (Django/Flask), Go, atau Java (Spring Boot).</p><p><b>2. REST API</b> — HTTP method, status code, authentication, versioning.</p><p><b>3. Database</b> — SQL (PostgreSQL, MySQL) + NoSQL (MongoDB, Redis).</p><p><b>4. Authentication</b> — JWT, OAuth, session.</p><p><b>5. ORM</b> — Prisma, Sequelize, atau Hibernate.</p><p><b>6. Testing</b> — Unit test, integration test, e2e test.</p><h2>FASE 3: DevOps (9-12 bulan)</h2><p><b>1. Linux basic</b> — command line, file permission, process management.</p><p><b>2. Docker</b> — container, image, compose.</p><p><b>3. CI/CD</b> — GitHub Actions, GitLab CI, atau Jenkins.</p><p><b>4. Cloud</b> — AWS, GCP, atau Vercel untuk frontend.</p><p><b>5. Monitoring</b> — logging, error tracking, performance monitoring.</p><h2>Soft Skills yang Wajib</h2><p>Komunikasi, teamwork, problem solving, kemampuan belajar cepat, dan <b>bahasa Inggris</b>.</p><h2>Tips Belajar</h2><p>1. Fokus 1 stack dulu. 2. Bangun 5 proyek portfolio. 3. Kontribusi ke open source kecil. 4. Ikut hackathon. 5. Bikin blog atau YouTube.</p><h2>Penutup</h2><p>Roadmap ini cuma peta. Kamu yang jalan. Yang penting: konsisten, selesai, dan terus belajar.</p>'},

  {id:'a4',title:'Cara Optimasi Performa Website agar Ngebut',type:'article',author:'Ysdev',date:'12 Sep 2026',read:11,
   excerpt:'Teknik-teknik bikin website kamu ngebut kayak kilat.',
   content:'<h2>Kenapa Performa Penting?</h2><p>Setiap 1 detik loading tambahan = 7% konversi hilang. Google juga pakai speed sebagai ranking factor. User yang nunggu lebih dari 3 detik = 53% bakal pergi.</p><h2>1. Optimasi Gambar</h2><p>Pakai format WebP/AVIF, compress dengan tools seperti Squoosh, lazy load di bawah fold. Gambar adalah penyebab utama website lelet — 60-70% bandwidth.</p><p>Contoh: gambar 2MB bisa jadi 200KB kalau dioptimasi. 10x lebih cepat!</p><h2>2. Minify CSS & JS</h2><p>Hapus spasi, komentar, karakter tidak perlu. Ukuran file turun 30-50%. Pakai tools seperti Terser (JS) atau CSSNano (CSS).</p><h2>3. Gunakan CDN</h2><p>Content Delivery Network nyimpen file di server terdekat user. Latency turun drastis. Cloudflare, BunnyCDN, atau jsDelivr untuk library.</p><h2>4. Cache Everything</h2><p>Browser cache, server cache, database cache, CDN cache. Cache = kunci performa. Set header <code>Cache-Control: max-age=31536000</code> untuk file static.</p><h2>5. Kurangi HTTP Request</h2><p>Gabungkan CSS, JS. Pakai sprite untuk icon. Kecil-kecil banyak = lambat. 1 file 500KB lebih cepat dari 50 file 10KB.</p><h2>6. Defer & Async JavaScript</h2><p>Jangan block rendering. Pakai <code>defer</code> atau <code>async</code> untuk script non-kritis. Script yang block = user nunggu kosong.</p><h2>7. Optimasi Font</h2><p>Pakai <code>font-display: swap</code>, subset (hanya karakter yang dipakai), format woff2. Font sering jadi bottleneck tanpa disadari.</p><h2>8. Code Splitting</h2><p>Pecah bundle besar jadi chunk kecil. User cuma download yang dibutuhkan.</p><h2>9. Preload & Prefetch</h2><p>Beri tahu browser resource mana yang penting. <code>&lt;link rel="preload"&gt;</code> untuk critical resource.</p><h2>10. Audit Reguler</h2><p>Pakai Lighthouse atau PageSpeed Insights tiap 2 minggu. Track performa jadi kebiasaan.</p><h2>Penutup</h2><p>Optimasi itu proses, bukan sekali jadi. Mulai dari yang paling berdampak (gambar & cache), lalu iterasi.</p>'},

  {id:'a5',title:'Panduan Git & Version Control untuk Pemula',type:'article',author:'Ysdev',date:'10 Sep 2026',read:13,
   excerpt:'Semua perintah Git yang kamu butuhkan sehari-hari.',
   content:'<h2>Apa itu Git?</h2><p>Git adalah sistem version control yang melacak setiap perubahan file. Bayangkan seperti "save point" di game — kamu bisa balik ke versi lama kapan saja.</p><h2>Kenapa Wajib?</h2><p>1. Backup otomatis di cloud. 2. Kolaborasi dengan tim. 3. Coba-coba tanpa takut rusak. 4. Portfolio publik.</p><h2>Setup Awal</h2><pre><code>git config --global user.name "Nama Kamu"\ngit config --global user.email "email@kamu.com"</code></pre><h2>Alur Dasar</h2><p><b>1. Inisialisasi repo:</b></p><pre><code>git init</code></pre><p><b>2. Cek status:</b></p><pre><code>git status</code></pre><p><b>3. Stage perubahan:</b></p><pre><code>git add .</code></pre><p><b>4. Commit:</b></p><pre><code>git commit -m "pesan commit"</code></pre><p><b>5. Push ke remote:</b></p><pre><code>git push origin main</code></pre><h2>Branching</h2><p>Branch = cabang pengembangan. Setiap fitur baru punya branch sendiri.</p><pre><code>git branch fitur-login\ngit checkout fitur-login\n# atau\ngit checkout -b fitur-login</code></pre><p>Setelah selesai:</p><pre><code>git checkout main\ngit merge fitur-login</code></pre><h2>Perintah Sering Dipakai</h2><p><code>git log --oneline</code> — lihat history<br><code>git pull</code> — ambil update<br><code>git diff</code> — lihat perubahan<br><code>git stash</code> — simpan sementara<br><code>git reset HEAD~1</code> — undo commit terakhir</p><h2>Tips</h2><p>1. Commit kecil-kecil, pesan jelas.<br>2. Jangan commit password atau API key.<br>3. Pull dulu sebelum push.<br>4. Pakai .gitignore.</p><h2>Penutup</h2><p>Git itu skill wajib. 2 hari belajar, seumur hidup pakai.</p>'},

  {id:'a6',title:'Docker untuk Developer Modern',type:'article',author:'Ysdev',date:'8 Sep 2026',read:14,
   excerpt:'Kenapa Docker wajib dikuasai developer 2026.',
   content:'<h2>Apa itu Docker?</h2><p>Docker = container. Bayangkan seperti kotak yang berisi aplikasi + semua dependensinya. Jalan di mana aja hasilnya sama.</p><h2>Masalah yang Diselesaikan</h2><p>"Di laptop gue jalan, di server nggak." Docker menyelesaikan ini. Setiap aplikasi jalan di lingkungan terisolasi.</p><h2>Konsep Dasar</h2><p><b>Image</b> — template aplikasi (seperti blueprint).<br><b>Container</b> — instance image yang jalan (seperti rumah).<br><b>Dockerfile</b> — resep bikin image.<br><b>Volume</b> — penyimpanan persisten.<br><b>Registry</b> — tempat nyimpen image (Docker Hub).</p><h2>Perintah Dasar</h2><pre><code># Build image\ndocker build -t myapp .\n\n# Run container\ndocker run -p 8080:80 myapp\n\n# Lihat container jalan\ndocker ps\n\n# Stop container\ndocker stop [id]\n\n# Hapus container\ndocker rm [id]</code></pre><h2>Dockerfile Contoh</h2><pre><code>FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]</code></pre><h2>Docker Compose</h2><p>Untuk manage multi-container (app + db + cache) dalam 1 file YAML.</p><pre><code>version: "3"\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    depends_on:\n      - db\n  db:\n    image: postgres:15\n    environment:\n      POSTGRES_PASSWORD: rahasia</code></pre><h2>Kelebihan</h2><p>1. Konsisten di semua environment.<br>2. Cepat startup.<br>3. Ringan (share OS kernel).<br>4. Mudah scaling.</p><h2>Penutup</h2><p>Docker itu standar industri. Invest 1 minggu belajar = hemat berbulan-bulan debugging.</p>'},

  {id:'a7',title:'Algoritma & Struktur Data — Fundamental Penting',type:'article',author:'Ysdev',date:'5 Sep 2026',read:16,
   excerpt:'Fundamental yang membedakan programmer biasa dan hebat.',
   content:'<h2>Kenapa Penting?</h2><p>Algoritma & struktur data bukan hafalan. Ini cara berpikir. Bikin kode kamu efisien, cepat, hemat memori. Skill yang membedakan junior dan senior.</p><h2>Struktur Data Esensial</h2><p><b>Array</b> — akses cepat O(1), insert lambat O(n).<br><b>Linked List</b> — insert/delete cepat O(1), akses lambat O(n).<br><b>Stack</b> — LIFO (Last In First Out).<br><b>Queue</b> — FIFO (First In First Out).<br><b>HashMap</b> — key-value O(1), paling sering dipakai.<br><b>Tree</b> — hierarki (file system, DOM).<br><b>Graph</b> — relasi kompleks (sosial media, maps).</p><h2>Algoritma Wajib</h2><p><b>Sorting:</b> Bubble (O(n²)), Merge (O(n log n)), Quick (O(n log n)).<br><b>Searching:</b> Linear (O(n)), Binary (O(log n)).<br><b>Recursion</b> — fungsi panggil diri sendiri.<br><b>Dynamic Programming</b> — simpan hasil untuk hindari hitung ulang.<br><b>Greedy</b> — pilih terbaik saat itu.<br><b>BFS & DFS</b> — traversal graph.</p><h2>Big O Notation</h2><p>Cara ukur efisiensi algoritma.<br>O(1) — konstan (terbaik)<br>O(log n) — logaritmik<br>O(n) — linear<br>O(n log n) — linearitmik<br>O(n²) — kuadratik (hindari!)<br>O(2ⁿ) — eksponensial (horor)</p><h2>Cara Belajar</h2><p>1. Pahami konsep dulu, jangan hafal.<br>2. Implementasi sendiri (bukan copy).<br>3. Practice di LeetCode/HackerRank.<br>4. Mulai dari Easy, naik bertahap.</p><h2>Penutup</h2><p>Algoritma = otot. Latihan rutin = kuat. Interview FAANG selalu tes ini.</p>'},

  {id:'a8',title:'Belajar React dari Nol sampai Bisa',type:'article',author:'Ysdev',date:'3 Sep 2026',read:15,
   excerpt:'Panduan lengkap React untuk pemula yang sudah paham JavaScript.',
   content:'<h2>Prerequisite</h2><p>Sebelum belajar React, kamu harus sudah paham: HTML, CSS, JavaScript (variabel, fungsi, array, object, ES6+), dan DOM manipulation.</p><h2>Apa itu React?</h2><p>React = library JavaScript untuk bikin UI. Dibuat Facebook. Konsep utama: komponen & state.</p><h2>Setup</h2><pre><code>npm create vite@latest myapp -- --template react\ncd myapp\nnpm install\nnpm run dev</code></pre><h2>Komponen</h2><p>Komponen = potongan UI yang reusable.</p><pre><code>function Hello({nama}) {\n  return &lt;h1&gt;Halo, {nama}!&lt;/h1&gt;;\n}\n\nfunction App() {\n  return (\n    &lt;div&gt;\n      &lt;Hello nama="Yadi" /&gt;\n      &lt;Hello nama="Ani" /&gt;\n    &lt;/div&gt;\n  );\n}</code></pre><h2>State</h2><p>State = data yang berubah.</p><pre><code>import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    &lt;button onClick={() =&gt; setCount(count + 1)}&gt;\n      Klik {count}\n    &lt;/button&gt;\n  );\n}</code></pre><h2>useEffect</h2><p>Untuk side effect (fetch API, subscription).</p><pre><code>useEffect(() =&gt; {\n  fetch("/api/data")\n    .then(r =&gt; r.json())\n    .then(setData);\n}, []);</code></pre><h2>Routing</h2><pre><code>npm install react-router-dom</code></pre><h2>State Management</h2><p>Untuk app besar, pakai Redux, Zustand, atau Context API.</p><h2>Tips</h2><p>1. Jangan over-engineer.<br>2. Pakai functional component + hooks.<br>3. Split komponen kecil.<br>4. Custom hook untuk logic reuse.</p><h2>Penutup</h2><p>React itu tools. Yang penting logika. Kuasai JavaScript dulu, React mudah.</p>'},

  // ==================== BERITA ====================
  {id:'b1',title:'AI Generatif Mengubah Dunia Kerja 2026',type:'berita',author:'Redaksi',date:'22 Sep 2026',read:8,
   excerpt:'Survei global: 68% developer sudah pakai AI assistant harian.',
   content:'<p><b>JAKARTA</b> — Survei terbaru dari komunitas developer global menunjukkan 68% programmer sudah menggunakan AI assistant dalam pekerjaan harian mereka. Angka ini naik 3x lipat dibanding 2 tahun lalu.</p><p>AI sekarang dipakai untuk: menulis boilerplate code, review PR, debugging, sampai dokumentasi otomatis. Perusahaan besar seperti Microsoft, Google, dan startup lokal sudah mengintegrasikan AI ke workflow.</p><p>"AI bukan pengganti developer, tapi amplifier. Yang bisa pakai AI akan mengalahkan yang tidak," kata seorang senior engineer di konferensi teknologi Jakarta.</p><p>Dampak ke industri: permintaan skill AI prompt engineering naik drastis. Perusahaan mulai investasi training AI untuk tim. Gaji untuk posisi "AI-augmented developer" naik 20-30% dibanding developer biasa.</p><p>Yang perlu diwaspadai: ketergantungan berlebihan. Beberapa perusahaan melaporkan junior developer jadi lemah fundamental karena selalu pakai AI. "AI itu alat, bukan tongkat," tegas seorang CTO.</p><p>Ke depan, diprediksi AI akan jadi bagian default dari setiap IDE. Yang tidak bisa pakai AI akan tertinggal.</p>'},

  {id:'b2',title:'Startup Lokal Raih Pendanaan Rp 500 M',type:'berita',author:'Redaksi',date:'20 Sep 2026',read:6,
   excerpt:'Startup edtech asal Surabaya menembus pasar Asia Tenggara.',
   content:'<p><b>SURABAYA</b> — Sebuah startup edtech lokal berhasil meraih pendanaan seri B sebesar Rp 500 miliar. Dana akan dipakai ekspansi ke 5 negara Asia Tenggara: Malaysia, Singapura, Thailand, Vietnam, dan Filipina.</p><p>Produk mereka: platform belajar coding interaktif dengan gamifikasi. Sudah dipakai 2 juta pelajar di Indonesia sejak 2023.</p><p>"Fokus kami bukan cuma konten, tapi engagement. Belajar harus kayak main game," ujar CEO-nya dalam wawancara eksklusif.</p><p>Yang membedakan: mereka pakai AI untuk personalisasi pembelajaran. Setiap siswa punya learning path unik.</p><p>Investor percaya pasar edtech Indonesia masih punya ruang tumbuh besar. Baru 15% pelajar Indonesia yang akses platform digital.</p><p>Rencana 2027: masuk ke Jepang dan Korea Selatan.</p>'},

  {id:'b3',title:'Bahasa Pemrograman Paling Dicari 2026',type:'berita',author:'Redaksi',date:'18 Sep 2026',read:7,
   excerpt:'Python masih juara, tapi Rust dan Go naik pesat.',
   content:'<p><b>Data</b> dari laporan industri menunjukkan urutan bahasa pemrograman paling dicari di 2026:</p><p>1. <b>Python</b> — dominasi AI/ML<br>2. <b>JavaScript/TypeScript</b> — web everywhere<br>3. <b>Java</b> — enterprise tetap kuat<br>4. <b>Go</b> — backend & cloud<br>5. <b>Rust</b> — sistem & performance<br>6. <b>Kotlin</b> — Android modern<br>7. <b>Swift</b> — iOS</p><p>Menariknya, Rust dan Go naik paling cepat. Rust jadi bahasa favorit developer 5 tahun berturut-turut di Stack Overflow survey. Go dipakai hampir semua startup cloud.</p><p>Yang turun: PHP, Ruby, Perl. Bukan berarti mati, tapi permintaan turun.</p><p>Tips: pilih bahasa sesuai tujuan. Untuk AI → Python. Untuk web → JavaScript. Untuk mobile → Kotlin/Swift. Untuk sistem → Rust/C++.</p>'},

  {id:'b4',title:'Kesehatan Mental Programmer Jadi Sorotan',type:'berita',author:'Redaksi',date:'15 Sep 2026',read:8,
   excerpt:'Burnout jadi masalah serius di industri teknologi.',
   content:'<p><b>Diskusi</b> soal burnout di kalangan developer semakin ramai. Survei internal perusahaan teknologi besar menunjukkan 42% engineer pernah alami burnout dalam 2 tahun terakhir.</p><p>Penyebab: deadline ketat, on-call 24/7, dan budaya kerja berlebihan. Ditambah pandemi yang blur batas kerja-rumah.</p><p>Beberapa perusahaan mulai adopsi kebijakan: no-meeting-day, cuti mental health, dan limit jam kerja.</p><p>"Produktivitas jangka panjang lebih penting dari sprint sesaat," ujar seorang VP Engineering di sebuah unicorn Asia Tenggara.</p><p>Tips untuk developer: 1. Istirahat rutin. 2. Olahraga. 3. Jangan cek kerja di luar jam. 4. Bicara kalau overwhelmed.</p><p>Kesadaran soal kesehatan mental developer naik. Yang dulu tabu, sekarang jadi topik normal.</p>'},

  {id:'b5',title:'Web3 & Blockchain: Masih Relevan?',type:'berita',author:'Redaksi',date:'12 Sep 2026',read:9,
   excerpt:'Setelah hype 2021, ke mana arah Web3 sekarang?',
   content:'<p><b>Analisis</b> — Setelah euforia 2021, Web3 masuk fase realistis. Banyak proyek mati, tapi yang survive mulai punya use case nyata.</p><p>Yang bertahan: stablecoin untuk pembayaran cross-border, NFT untuk ticketing & membership, dan smart contract untuk supply chain.</p><p>Yang lesu: metaverse virtual land (harga turun 90% dari puncak), P2E game tanpa gameplay (kebanyakan mati).</p><p>"Hype boleh lewat, tapi teknologi dasarnya tetap berkembang. Blockchain tetap jadi solusi untuk trust-less system," ujar seorang peneliti.</p><p>Regulasi di Indonesia masih abu-abu. Pemerintah sedang susun framework. Beberapa perusahaan kripto lokal sudah dapat lisensi.</p><p>Kesimpulan: Web3 bukan mati, cuma kembali ke realita. Yang bisa deliver value akan bertahan.</p>'},

  {id:'b6',title:'Cloud Computing: AWS vs GCP vs Azure',type:'berita',author:'Redaksi',date:'10 Sep 2026',read:10,
   excerpt:'Perbandingan 3 cloud provider terbesar di 2026.',
   content:'<p><b>Perbandingan</b> — Cloud market masih dikuasai 3 raksasa. Berikut perbandingan untuk developer Indonesia:</p><p><b>AWS (Amazon)</b> — Market leader (32%). Paling banyak service, dokumentasi lengkap. Cocok untuk enterprise. Kelemahan: kompleks, mahal untuk pemula.</p><p><b>Azure (Microsoft)</b> — 23% market. Integrasi kuat dengan Windows & Office. Cocok untuk perusahaan yang sudah pakai Microsoft.</p><p><b>GCP (Google)</b> — 11% market. Paling developer-friendly. AI/ML tools terbaik. Cocok untuk startup & data science.</p><p>Untuk pemula, rekomendasi: mulai dari <b>Vercel</b> (frontend) atau <b>Railway</b> (backend). Baru naik ke AWS/GCP/Azure kalau perlu.</p><p>Tips hemat: 1. Pakai free tier. 2. Monitor billing. 3. Matikan resource idle. 4. Pakai reserved instance untuk jangka panjang.</p>'},

  // ==================== NOVEL ====================
  {id:'n1',title:'Petualangan di Negeri Kode — Bab 1: Gerbang',type:'novel',author:'Ysdev',date:'19 Sep 2026',read:15,
   excerpt:'Seorang pemuda tersedot ke dunia yang dibangun dari kode.',
   content:'<p><i>Malam itu hujan turun deras. Andi masih di depan laptop, mencoba memperbaiki bug yang tak kunjung hilang. Jam sudah menunjukkan 02:47.</i></p><p>"Sial," gumamnya. Baris ke-247 masih merah. Sudah 3 jam dia stuck di error yang sama: <code>NullPointerException</code>.</p><p>Kopi dingin di sampingnya sudah tandas. Mata perih. Tapi besok deadline. Dia harus selesai malam ini.</p><p>Tiba-tiba layar berkedip. Bukan kedip biasa — seluruh monitor menyala putih, lalu ada teks muncul: <b>"Selamat datang, Andi."</b></p><p>Andi mengerjapkan mata. "Halusinasi," pikirnya. Tapi teks itu muncul lagi, lebih jelas: <b>"Kamu yang selama ini mencari. Masuklah."</b></p><p>Belum sempat Andi bereaksi, tubuhnya terasa ringan. Lantai kamar menghilang. Dia jatuh... ke dalam cahaya.</p><p>Ketika membuka mata, dia berdiri di padang rumput digital. Langit berwarna <code>#0a0e27</code>. Pohon-pohon berbentuk <code>{ }</code>. Ada sungai mengalir dengan teks biru.</p><p>"Apa-apaan ini?" Andi menoleh. Seekor rubah neon mendekat, matanya seperti terminal.</p><p>"Kamu pemanggil baru ya?" kata rubah itu. Suaranya terdengar seperti suara robot yang ramah. "Selamat datang di Negeri Kode. Di sini, setiap baris yang kamu tulis jadi kenyataan."</p><p>Andi mundur selangkah. "Aku... aku harus pulang."</p><p>"Pulang?" Rubah itu tertawa. "Tidak bisa. Kecuali kamu selesaikan Quest Utama. Tapi tenang, aku akan jadi pemandumu. Namaku Compilo."</p><p>Langit di atas mereka berubah gelap. Ada guntur.</p><p>"Apa itu?" tanya Andi.</p><p>"Itu <b>Compiler</b>. Dia yang jaga gerbang. Kalau kamu mau pulang, kamu harus mengalahkannya."</p><p>Compilo menatap Andi serius. "Tapi sebelum itu, kamu harus kuat. Ayo, aku antar ke desa terdekat. Kamu harus latihan."</p><p><i>Bersambung ke Bab 2...</i></p>'},

  {id:'n2',title:'Petualangan di Negeri Kode — Bab 2: Sintaksia',type:'novel',author:'Ysdev',date:'21 Sep 2026',read:15,
   excerpt:'Andi bertemu guild pertama dan harus menyelesaikan quest pertama.',
   content:'<p><i>Rubah neon itu bernama Compilo. Dia memandu Andi ke desa terdekat. Perjalanan 30 menit terasa seperti berjam-jam.</i></p><p>Desa itu bernama "Sintaksia". Rumah-rumahnya terbuat dari balok kayu bertekstur kode. Setiap pintu punya <code>handleClick()</code> di gagangnya.</p><p>"Kamu harus daftar ke guild," kata Compilo. "Pilih satu: Frontend, Backend, atau Fullstack."</p><p>Andi bingung. "Apa bedanya?"</p><p>"Frontend = yang bertarung di depan, bikin tampilan. Backend = yang atur strategi dari balik layar. Fullstack = bisa keduanya, tapi harus lebih kuat."</p><p>Andi memilih <b>Fullstack</b>. Compilo mengangguk. "Pilihan berani. Sekarang quest pertama: temukan Bug di Hutan Loop."</p><p>Di hutan, Andi bertemu makhluk-makhluk aneh: <i>NullPointer</i> — bayangan hitam yang suka menghilang, <i>StackOverflow</i> — monster yang memanggil dirinya sendiri berkali-kali, dan <i>InfiniteLoop</i> — ular raksasa yang menggigit ekornya sendiri.</p><p>InfiniteLoop paling berbahaya. Dia berputar tanpa henti, menghisap energi siapa pun yang dekat.</p><p>"Kamu harus <code>break</code> dia," bisik Compilo. "Atau <code>return</code> sebelum dia selesai."</p><p>Andi mengangkat tangan. Di telapak tangannya muncul tombol keyboard transparan. Dia menulis: <code>while(true) { if (musuh.lelah) break; }</code></p><p>InfiniteLoop melambat. Pelan-pelan berputar makin lambat. Lalu berhenti.</p><p>"Bagus," kata Compilo. "Kamu punya insting."</p><p>Andi tersenyum. Untuk pertama kalinya sejak tiba di dunia ini, dia merasa... tertantang.</p><p><i>Bersambung ke Bab 3...</i></p>'},

  {id:'n3',title:'Petualangan di Negeri Kode — Bab 3: Compiler',type:'novel',author:'Ysdev',date:'22 Sep 2026',read:18,
   excerpt:'Andi melawan Compiler dan menemukan kekuatan barunya.',
   content:'<p><i>Angin bertiup. Daun-daun digital beterbangan. InfiniteLoop sudah kalah. Tapi langit masih gelap.</i></p><p>Compiler muncul dari balik awan. Bentuknya seperti raksasa yang terbuat dari teks berjalan. Setiap gerakannya mengeluarkan error message.</p><p>"ERROR: Unauthorized access to this world," gumamnya dengan suara menggelegar.</p><p>Andi mundur. "Apa yang harus aku lakukan?"</p><p>"Compile ulang dirimu," jawab Compilo. "Compiler hanya bisa dilawan dengan kode yang sudah di-compile sempurna."</p><p>Andi berpikir. Dia ingat semua pelajaran coding yang pernah dia baca. Dari variabel sampai algoritma. Dari loop sampai rekursi.</p><p>Dia mengangkat tangan. Kali ini bukan satu tombol, tapi seluruh keyboard muncul di udara.</p><p>Dia menulis:</p><pre><code>class Andi {\n  power = 100;\n  skill = ["debug", "optimize", "refactor"];\n  \n  fight(enemy) {\n    while (enemy.alive) {\n      this.attack(enemy);\n      if (enemy.weak) this.special();\n    }\n  }\n}</code></pre><p>Cahaya biru menyelimuti tubuh Andi. Kekuatannya bertambah.</p><p>"Sekarang!" seru Compilo.</p><p>Andi melompat. Compiler menyerang dengan error message. Andi menghindar, lalu balas dengan <b>Refactor Blast</b>. Compiler goyah.</p><p>Serangan kedua: <b>Optimize Slash</b>. Compiler makin lemah.</p><p>Serangan terakhir: <b>Debug Beam</b>. Compiler hancur jadi serpihan cahaya.</p><p>Langit kembali cerah. Di kejauhan, muncul gerbang bercahaya — gerbang pulang.</p><p>"Kamu berhasil," kata Compilo. "Tapi ingat, ini bukan akhir. Ini awal."</p><p>"Maksudmu?"</p><p>"Kamu bisa kembali kapan saja. Negeri Kode selalu butuh penjaga baru. Dan kamu... cocok."</p><p>Andi tersenyum. Dia berjalan ke gerbang. Sebelum masuk, dia menoleh. "Terima kasih, Compilo."</p><p>Rubah neon itu mengangguk. "Sampai jumpa, Andi."</p><p>Andi melangkah ke dalam cahaya. Ketika membuka mata, dia ada di depan laptopnya. Jam menunjukkan 03:15. Error NullPointer tadi... sudah hilang. Diganti dengan solusi yang dia tulis di Negeri Kode.</p><p>Andi tersenyum. Dia tahu, ini bukan mimpi.</p><p><b>TAMAT</b></p><p><i>Bersambung ke Seri 2: "Negeri Framework"...</i></p>'},

  {id:'n4',title:'Negeri Framework — Bab 1: React Realm',type:'novel',author:'Ysdev',date:'23 Sep 2026',read:16,
   excerpt:'Sekuel baru: Andi kembali ke Negeri Kode dengan misi baru.',
   content:'<p><i>Tiga bulan setelah petualangan pertama, Andi kembali ke Negeri Kode. Kali ini bukan karena kecelakaan. Dia sengaja.</i></p><p>Compilo menyambutnya di gerbang. "Kamu kembali. Aku tahu."</p><p>"Ada apa?" tanya Andi. "Kamu yang panggil aku, kan?"</p><p>"Iya. Ada masalah besar. Negeri Framework sedang runtuh."</p><p>Compilo menjelaskan: Negeri Kode punya banyak wilayah. Sintaksia (tempat Andi pertama kali datang), Loop Mountains, Stack Valley, dan yang paling besar: <b>Frameworkia</b>.</p><p>"Frameworkia terbagi jadi 3 kerajaan: React Realm, Vue Village, dan Angular Empire. Ketiganya dulunya damai. Sekarang perang."</p><p>"Kenapa?"</p><p>"Karena ada yang bilang salah satu framework lebih baik. Fanatisme. Ini bikin energi Negeri Framework kacau."</p><p>Andi menghela napas. "Jadi misi aku: damaikan mereka?"</p><p>"Ya. Tapi hati-hati. Ada <b>Fake Dev</b> yang sengaja bikin kekacauan. Dia bukan programmer asli, cuma suka bikin drama."</p><p>Andi mengangguk. Dia melangkah ke portal menuju React Realm.</p><p>Ketika tiba, dia disambut hutan komponen. Setiap pohon adalah <code>&lt;Component /&gt;</code>. Ada sungai state mengalir.</p><p>"Siapa kamu?" Seorang penjaga menghadang. Namanya <b>Hooks</b>. Dia pakai pakaian berwarna biru React.</p><p>"Aku Andi. Aku ke sini untuk damai."</p><p>"Damai?" Hooks tertawa pahit. "Vue dan Angular sudah kirim pasukan. Besok perang."</p><p>Andi tahu ini sulit. Tapi dia punya kekuatan: <b>kode yang bisa menyelesaikan masalah, bukan bikin masalah</b>.</p><p><i>Bersambung...</i></p>'},

  {id:'n5',title:'Negeri Framework — Bab 2: Damai di Frameworkia',type:'novel',author:'Ysdev',date:'24 Sep 2026',read:18,
   excerpt:'Andi menyatukan 3 kerajaan dan menghadapi Fake Dev.',
   content:'<p><i>Malam sebelum perang. Andi duduk di atas menara React, memandang horizon Frameworkia.</i></p><p>Compilo muncul di sampingnya. "Kamu yakin bisa?"</p><p>"Tidak," jawab Andi jujur. "Tapi aku harus coba."</p><p>Dia punya rencana: bicara ke ketiga raja. Bukan untuk memilih yang terbaik, tapi untuk menyadarkan mereka bahwa <b>framework itu cuma alat</b>.</p><p>Pagi. Ketiga pasukan berkumpul di Dataran Compile.</p><p>React Realm dengan pasukan Hooks dan Component. Vue Village dengan pasukan Directive dan Reactive. Angular Empire dengan pasukan Service dan Module.</p><p>Ketiga raja angkat senjata. "Serang!"</p><p>Andi melompat ke tengah. "STOP!"</p><p>Semua terdiam.</p><p>"Kenapa kalian perang?" tanya Andi. "Karena kalian pikir framework kalian yang terbaik? Tapi kalian semua sama. Kalian semua bikin web."</p><p>"React paling fleksibel!" kata Raja Hooks.</p><p>"Vue paling gampang!" kata Raja Directive.</p><p>"Angular paling lengkap!" kata Raja Service.</p><p>"Betul semua," kata Andi. "Tapi yang terbaik itu... <b>yang sesuai kebutuhan</b>. Bukan yang paling keren di mata orang."</p><p>Kata-kata Andi membuat ketiga raja berpikir.</p><p>Tiba-tiba, dari balik bayangan, muncul sosok gelap. <b>Fake Dev</b>.</p><p>"Jangan dengarkan dia!" serunya. "Dia cuma mau damai karena lemah!"</p><p>Andi menatap Fake Dev. "Kamu siapa?"</p><p>"Aku adalah suara di internet yang selalu bilang framework orang lain jelek. Aku yang bikin kalian perang."</p><p>"Kenapa?"</p><p>"Karena aku tidak bisa bikin kode. Jadi aku bikin drama. Biar orang sibuk berantem, sementara aku... menonton."</p><p>Ketiga raja terkejut. Mereka sadar telah dipermainkan.</p><p>Andi mengangkat tangan. "Kita bersatu. Bukan untuk perang. Untuk bikin web yang bagus."</p><p>Ketiga raja saling menatap. Lalu mereka mengangguk.</p><p>Fake Dev melarikan diri. Tapi tidak perlu dikejar — dia akan hilang sendiri, karena dia tidak punya kode untuk dijalankan.</p><p>Frameworkia kembali damai. Ketiga kerajaan bersatu, tapi tetap punya identitas masing-masing.</p><p>Compilo mendekat. "Kamu hebat, Andi."</p><p>"Aku cuma ngomong," jawab Andi. "Kode yang hebat itu bukan yang paling rumit, tapi yang menyelesaikan masalah."</p><p>Andi membuka portal pulang. Tapi sebelum masuk, dia menatap Frameworkia sekali lagi. Damai. Damai yang dibuat dengan logika, bukan perang.</p><p><b>TAMAT</b></p><p><i>Seri 3 akan datang: "Negeri Database"...</i></p>'}
];

function ensureArticles(){
  const existing = DB.get('articles', null);
  if (!existing || existing.length < 20) {
    DB.set('articles', DEFAULT_ARTICLES);
  }
  return DB.get('articles', []);
}

function renderArticle(){
  const grid = document.getElementById('articleGrid');
  if (!grid) return;
  let arts = ensureArticles();
  const q = (document.getElementById('searchArticle')?.value || '').toLowerCase();
  const type = document.getElementById('filterType')?.value || '';
  if (q) arts = arts.filter(a => a.title.toLowerCase().includes(q) || a.excerpt.toLowerCase().includes(q));
  if (type) arts = arts.filter(a => a.type === type);
  if (arts.length === 0){ grid.innerHTML = '<p style="color:var(--text-muted);text-align:center;padding:40px">Tidak ada hasil.</p>'; return }
  grid.innerHTML = arts.map(a => '<div class="article-card" onclick="openReader(\''+a.id+'\')">' +
    '<span class="article-type type-'+a.type+'">'+a.type+'</span>' +
    '<h3>'+a.title+'</h3><p class="article-excerpt">'+a.excerpt+'</p>' +
    '<div style="display:flex;justify-content:space-between;align-items:center;margin-top:14px">' +
      '<p class="article-author">✍️ '+a.author+'</p>' +
      '<p class="article-author">📖 '+a.read+' min</p>' +
    '</div></div>').join('');
}

function openReader(id){
  const a = ensureArticles().find(x => x.id === id);
  if (!a) return;
  trackView('article', id);
  document.getElementById('readerContent').innerHTML =
    '<div class="reader-content"><h1>'+a.title+'</h1>' +
    '<p class="meta"><span class="article-type type-'+a.type+'">'+a.type+'</span> • '+a.author+' • '+a.date+' • '+a.read+' min baca</p>' +
    '<div class="body">'+a.content+'</div></div>';
  document.getElementById('readerModal').classList.add('open');
}
function closeReader(){ document.getElementById('readerModal').classList.remove('open') }

document.addEventListener('DOMContentLoaded', renderArticle);
